# Generated by Django 3.2.13 on 2022-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=123, upload_to='images'),
            preserve_default=False,
        ),
    ]
